site_name: Christian Henkel 
site_description: an example blog set up following the blog tutorials
site_url: http://www.example.com

theme:
  name: material
  custom_dir: overrides
  repo_url: https://github.com/ct2034/hcde
  # features:
  #   - navigation.indexes
  logo: imgs/exclamation-question-mark_serenity-os.png
  favicon: imgs/exclamation-question-mark_serenity-os.png
  font:
    text: Funnel Sans
    code: Roboto Mono
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/wand-magic-sparkles
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: teal
      accent: red
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: red
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to system preference

plugins:
  - search
  - blog:
      enabled: true
      blog_dir: .
      blog_toc: false
      archive: false
      author_profiles: false
      categories: true
      categories_url_format: "c/{slug}"
      categories_allowed:
        - Thinkoneering
        - CV
        # - Publication
      categories_toc: true
      # pagination_per_page: 5
      # archive_pagination_per_page: 10
      # categories_pagination_per_page: 10
      # post_slugify: !!python/object/apply:ext.slugs.slugify
      #   kwds:
      #     short: true
  # - meta
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  # - awesome-pages:
  #     enabled: true
  #     strict: true
  #     # icons: fontawesome

extra:
  social:  
    - icon: fontawesome/brands/github
      link: https://github.com/ct2034
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/henkelchristian/
    - icon: fontawesome/brands/mastodon
      link: https://chaos.social/@ct2034
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/ct2034.bsky.social

# copyright: 
# Note: copyright is defined in overrides/partials/copyright.html

# hooks:
#   - hooks/socialmedia.py

markdown_extensions:
  # - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - neoteroi.timeline
  - meta

nav:
  # - Home: 
  # - Home: index.md
  # - Tags: tags.md
  # - Blog:
  #    - blog/index.md
  #    - blog/tags.md
  # - Publications: publications.md
  # - Thinkoneering: c/thinkoneering
  - Thinkoneering: c/thinkoneering/
  - CV: c/cv/
  - Publications: c/publications/
  # - tags.md
  - Publications (old): publications.md
  # - ...


extra_css:
  - https://fonts.googleapis.com/css?family=Domine
  - stylesheets/extra.css
  - stylesheets/neoteroi-v1.1.0.css
