site_name: Christian Henkel 
site_description: I work in robotics research. This is my personal site, combining scientific publications, CV entries, and blog posts.
site_author: Christian Henkel
site_url: https://thinkoneering.com

theme:
  name: material
  custom_dir: overrides
  repo_url: https://github.com/ct2034/hcde
  # features:
  #   - navigation.indexes
  logo: logo/ch.png
  favicon: logo/ch_32p.ico
  font:
    text: Funnel Sans
    code: Roboto Mono
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/wand-magic-sparkles
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue-grey
      accent: red
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: red
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to system preference

plugins:
  - search
  - blog:
      enabled: true
      blog_dir: .
      blog_toc: false
      post_url_date_format: "yy-MM-dd"
      post_url_format: "{categories}/{date}_{slug}"
      archive: false
      categories: true
      categories_url_format: "{slug}"
      categories_allowed:
        - Thinkoneering
        - CV
        - Publications
      categories_toc: true
      draft_on_serve: false
      pagination_per_page: 10
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "posts/ton/.*"
      date_from_meta:
        as_creation: "date" # means from page.meta.date
        as_update: "git" # means from git log
        datetime_format: "%Y-%m-%d %H:%M"
        default_time: "09:30"
        default_timezone: Europe/Paris
      use_git: true
      use_material_blog: true
      use_material_social_cards: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - bibtex:
      bib_file: bibtex/lit.bib
      csl_file: bibtex/chicago-author-date.csl
      # cite_inline: True   RuntimeError: Your version of pandoc (v2.9.2.1) is incompatible with the cite_inline feature.
      bib_by_default: True
  - redirects:
      redirect_maps:
        'autor/README.md': 'https://web.archive.org/web/20180823163315/http://thinkoneering.com/autor/'
        'blog/README.md': 'https://web.archive.org/web/20180823163315/http://thinkoneering.com/blog/'
        '2014/05/16/und-wozu-braucht-man-das/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2014/05/16/und-wozu-braucht-man-das/'
        '2014/06/06/kommunismus-im-internet/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2014/06/06/kommunismus-im-internet/'
        '2014/10/11/von-menschen-und-maschinen/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2014/10/11/von-menschen-und-maschinen/'
        '2014/10/31/turbovegetarier-ohne-facebook/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2014/10/31/turbovegetarier-ohne-facebook/'
        '2015/01/30/natur-und-technik/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2015/01/30/natur-und-technik/'
        '2015/03/16/die-3-stufen-der-open-source-liebe/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2015/03/16/die-3-stufen-der-open-source-liebe/'
        '2015/06/05/haus-am-see/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2015/06/05/haus-am-see/'
        '2015/06/21/anders-als-gedacht/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2015/06/21/anders-als-gedacht/'
        '2015/09/25/pflanze-dir-ein-winterkorn/README.md': 'https://web.archive.org/web/20190309125210/http://thinkoneering.com/2015/09/25/pflanze-dir-ein-winterkorn/'


extra:
  social:  
    - icon: fontawesome/brands/github
      link: https://github.com/ct2034
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/henkelchristian/
    - icon: fontawesome/brands/mastodon
      link: https://chaos.social/@ct2034
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/ct2034.bsky.social
  analytics:
    provider: google
    property: G-BVLSLET2CB
  consent:
    title: Cookie consent
    description: This website uses cookies to ensure you get the best experience.
    actions:
      - accept
      - manage
      - reject

markdown_extensions:
  # - neoteroi.timeline
  - meta
  - attr_list # [link text](https://target.link){target="_blank"}
  - footnotes # bibtex
  - pymdownx.blocks.admonition # /// define .... ///

nav:
  - Home: ../
  - Thinkoneering (Blog): thinkoneering/
  - CV: cv/
  - Publications: publications/
  - tags.md
  - about.md

extra_css:
  - https://fonts.googleapis.com/css?family=Domine
  - stylesheets/extra.css
  # - stylesheets/neoteroi-v1.1.0.css

watch:
  - overrides
  - overrides/partials
