site_name: Christian Henkel 
site_description: an example blog set up following the blog tutorials
site_url: http://www.example.com

theme:
  name: material
  custom_dir: overrides
  repo_url: https://github.com/ct2034/hcde
  # features:
  #   - navigation.indexes
  logo: logo/hc.png
  favicon: logo/hc_32p.ico
  font:
    text: Funnel Sans
    code: Roboto Mono
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/wand-magic-sparkles
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue-grey
      accent: red
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: red
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to system preference

plugins:
  - search
  - blog:
      enabled: true
      blog_dir: .
      blog_toc: false
      post_url_date_format: "yy-MM-dd"
      post_url_format: "{categories}/{date}_{slug}"
      archive: false
      categories: true
      categories_url_format: "{slug}"
      categories_allowed:
        - Thinkoneering
        - CV
        - Publications
      categories_toc: true
      draft_on_serve: false
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:  
    - icon: fontawesome/brands/github
      link: https://github.com/ct2034
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/henkelchristian/
    - icon: fontawesome/brands/mastodon
      link: https://chaos.social/@ct2034
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/ct2034.bsky.social
  analytics:
    provider: google
    property: G-BVLSLET2CB

markdown_extensions:
  # - neoteroi.timeline
  - meta

nav:
  - Home: ../
  - Thinkoneering (Blog): thinkoneering/
  - CV: cv/
  - Publications: publications/
  - tags.md
  - about.md

extra_css:
  - https://fonts.googleapis.com/css?family=Domine
  - stylesheets/extra.css
  # - stylesheets/neoteroi-v1.1.0.css

watch:
  - overrides/partials
