
name: Linter

on:
  push:
      branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Berlin"
      - uses: actions/checkout@v6
      - run: pip install -r requirements.txt
      - run: pip install pre-commit
      - name: Pre-commit
        run: pre-commit run -a
        env:
          SKIP: check-get-lit
